INSERT INTO QUOTE_INTRADAY (SYMBOL,PRICE) VALUES ('MSFT', 185.36);
INSERT INTO QUOTE_INTRADAY (SYMBOL,PRICE) VALUES ('GOOG', 1436.38);
INSERT INTO QUOTE_INTRADAY (SYMBOL,PRICE) VALUES ('TSLA', 882.96);
INSERT INTO QUOTE_INTRADAY (SYMBOL,PRICE) VALUES ('FB', 230.16);
INSERT INTO QUOTE_INTRADAY (SYMBOL,PRICE) VALUES ('NFLX', 421.97);

INSERT INTO QUOTE_EOD (SYMBOL,PRICE, REGION, REGION_TIME) VALUES ('MSFT', 186.36, 'BOSTON', CURRENT_TIMESTAMP() );
INSERT INTO QUOTE_EOD (SYMBOL,PRICE, REGION, REGION_TIME) VALUES ('GOOG', 1452.38, 'BOSTON', CURRENT_TIMESTAMP());
INSERT INTO QUOTE_EOD (SYMBOL,PRICE, REGION, REGION_TIME) VALUES ('TSLA', 892.96, 'BOSTON', CURRENT_TIMESTAMP());
INSERT INTO QUOTE_EOD (SYMBOL,PRICE, REGION, REGION_TIME) VALUES ('FB', 232.16, 'BOSTON', CURRENT_TIMESTAMP());
INSERT INTO QUOTE_EOD (SYMBOL,PRICE, REGION, REGION_TIME) VALUES ('NFLX', 422.97, 'BOSTON', CURRENT_TIMESTAMP());
