DROP TABLE IF EXISTS QUOTE_INTRADAY;
DROP TABLE IF EXISTS QUOTE_EOD;

CREATE TABLE QUOTE_INTRADAY(SYMBOL VARCHAR(16) NOT NULL PRIMARY KEY, PRICE DECIMAL(20, 5));
CREATE TABLE QUOTE_EOD(SYMBOL VARCHAR(16) NOT NULL PRIMARY KEY, PRICE DECIMAL(20, 5), REGION VARCHAR(16) NOT NULL, REGION_TIME VARCHAR(30) NOT NULL);